services:
  postgres:
    container_name: spring_testcontainers_db
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=blog'
      - 'POSTGRES_PASSWORD=secret_password'
      - 'POSTGRES_USER=blog'
    ports:
      - '5432'
